;; Prettify Symbol
(global-prettify-symbols-mode)
(setq prettify-symbols-alist
      '(("alpha" . ?α)
	("beta" . ?β)
	("gamma" . ?γ)
	("delta" . ?δ)
	("epsilon" . ?ε)
	("zeta" . ?ζ)
	("eta" . ?η)
	("theta" . ?θ)
	("iota" . ?ι)
	("kappa" . ?κ)
	("lambda" . ?λ)
	("mu" . ?μ)
	("nu" . ?ν)
	("xi" . ?ξ)
	("omicron" . ?ο)
	("pi" . ?π)
	("rho" . ?ρ)
	("sigma" . ?σ)
	("tau" . ?τ)
	("upsilon" . ?υ)
	("phi" . ?φ)
	("chi" . ?χ)
	("psi" . ?ψ)
	("omega" . ?ω)
	("sum" . ?∑)
	))


(provide 'init-prettify)
;; init-prettify ends here
